package helpers

import "strings"

func SuggestService(toComplete string) []string {
	services := []string{
		"Consulting",
		"Development",
		"Design",
		"Marketing",
		"Software Engineering",
		"Software Development",
		"Data Science",
		"Cloud Computing",
		"Security",
		"Project Management",
		"Quality Assurance",
		"Testing",
		"Training",
		"Technical Writing",
		"Site Reliability Engineering",
		"DevOps Consulting",
		"DevSecOps Consulting",
		"Web Development",
		"Mobile Development",
		"UI/UX Design",
		"Content Strategy",
		"Social Media Marketing",
		"Search Engine Optimization",
		"Analytics",
		"Database Administration",
		"Network Administration",
		"Virtualization",
		"Artificial Intelligence",
		"Machine Learning",
		"Natural Language Processing",
		"Blockchain Development",
		"IoT Development",
		"Cloud Infrastructure",
		"Cybersecurity",
		"Penetration Testing",
		"IT Auditing",
		"Compliance Consulting",
		"Regulatory Compliance",
		"Financial Consulting",
		"Tax Consulting",
		"Legal Consulting",
		"Intellectual Property Consulting",
		"Business Strategy Consulting",
		"Human Resources Consulting",
		"Talent Acquisition",
		"Performance Management",
		"Employee Engagement",
		"Leadership Development",
		"Organizational Development",
		"Change Management",
		"Executive Coaching",
		"Facilitation",
		"Training and Development",
		"Instructional Design",
		"E-learning",
		"Gamification",
		"Technical Training",
		"Soft Skills Training",
		"Public Speaking",
		"Writing and Editing",
		"Copywriting",
		"Technical Writing",
		"Grant Writing",
		"Editing",
		"Proofreading",
		"Translation",
		"Localization",
		"Interpretation",
		"Transcription",
		"Captioning",
		"Subtitling",
		"Voiceover",
		"Podcasting",
		"Audio Production",
		"Video Production",
		"Animation",
		"3D Modeling",
		"Graphic Design",
		"Logo Design",
		"Brand Identity",
		"Print Design",
		"Packaging Design",
		"Illustration",
		"Photography",
		"Videography",
		"Event Planning",
		"Wedding Planning",
		"Fundraising",
		"Nonprofit Consulting",
		"Volunteer Management",
		"Community Development",
		"Social Services",
		"Counseling",
		"Therapy",
		"Psychotherapy",
		"Psychiatry",
		"Nutrition",
		"Fitness",
		"Yoga",
		"Meditation",
		"Massage Therapy",
	}

	// Create a new slice to hold the matching suggestions.
	suggestions := make([]string, 0)

	// Check each service to see if it starts with the entered text.
	for _, service := range services {
		if strings.Contains(strings.ToLower(service), strings.ToLower(toComplete)) {
			suggestions = append(suggestions, service)
		}
	}

	return suggestions
}
